### ISSUE TITLE
Function unparsed-text-available() must have 2 arguments

### ISSUE THREAD

**Issue by mrft** [Saxonica/Saxon-CE#8]
If [this information](http://zvon.org/comp/r/ref-XSLT_2.html#Functions~unparsed-text-available) is correct then 
```XPath
unparsed-text-available($include-uri)
```
should work 

but it returns `Function unparsed-text-available() must have 2 arguments`

**Comment by michaelhkay** [comment]
I've logged it at https://saxonica.plan.io/issues/2434 and have committed a source patch (untested). We're don't have immediate plans to rebuild the product (running all the tests is very time-consuming) but perhaps someone else will.
