### ISSUE TITLE
document-uri(/) returns an empty string?

### ISSUE THREAD

**Issue by mrft** [Saxonica/Saxon-CE#9]
In the docs about [newXSLT20Processor](http://www.saxonica.com/ce/user-doc/1.1/html/api/saxon/newXSLT20Processor.html) I can see that 'By default, Saxon-CE uses the URI of the HTML page as the base URI for the stylesheet'

So when using Saxon.parseXML, and then trying to transform that document, I would expect similar behaviour. That would mean that using `document-uri(/)` in an XPath expression inside a stylesheet applied to that document would return 'the URI of the HTML page', but it actually seems to return an empty string (causing troubles in a resolve-uri call afterwards).

Could this be a bug? What if I want to do transformations on an xml file that doesn't exist on the server, and thus has no URI. Can I override this with my own value?

**Comment by michaelhkay** [comment]
I think this behaviour is correct. document-uri() is defined to return either (a) a URI that can be used to retrieve the document using the doc() function, or (b) if no such URI is available, nothing. In the case of a document constructed using parseXML(), there is no URI that satisfies (a), therefore document-uri() must return nothing.

**Comment by mrft** [comment]
I might be able to get things working if I use something like this:

```
blob = new Blob( [ xml ] )
xmlDoc = Saxon.requestXML( URL.createObjectURL( blob ) )
```

But if SaxonCE is behaving according to the spec, we can close this issue.
